### ISSUE TITLE
[Bug]: LinkedIn, Twitter and blog link not working

### ISSUE THREAD

**Issue by sumansahoo1** [krshkodes/krshkodes.co#7]
### Description

The links to the respective icons are not working

### To Reproduce

1. Go on to website 
2. Click on the respective links
3. See error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshkodes/krshkodes.co/blob/main/CODE_OF_CONDUCT.md)

**Comment by suman-somu** [comment]
I will make individual link an issue to solve a issue easily

**Comment by gptkrsh** [comment]
Thanks for pointing out, this should be fixed in the next version of the website

**Comment by gptkrsh** [comment]
Well, I just took a look, and it fixed here, so I'm just gonna close this issue ✅ Thank you for the issue
